### ISSUE TITLE
Number of lines for grid

### ISSUE THREAD

**Issue by ipshenicyn** [soanvig/mm-jsr#38]
Currently it's not impossible to set count of lines for grid. I found `return Math.round(100)` in your code ) 
I think, it's really important feature. It is for me, at least. 

Same thing is count of labels for grid. Now, the value is "each 10 lines". 

In my case it looks like this: http://bit.ly/2L4Jef4

I suggest, the script should calculate optimal count of lines and labels itself.

**Comment by soanvig** [comment]
Yes, this is true. I acknowledged the problem when I created this grid, but didn't do much about it. 

This is not that easy thing, because if we have slider of 100vw, then on large screen this grid will be OK, but on the smaller - not. This is why I dropped support for that initially.

I'll add labels to that issue, so grid (number of lines) will fit properly in different slider widths.

**Comment by soanvig** [comment]
**Description**:

This functionality should depend grid lines from slider width, listen on window resize, and fit accordingly.

**Comment by plumthedev** [comment]
I will take care of it

**Comment by soanvig** [comment]
This would be useful in v2
