### ISSUE TITLE
Provide compiled code / Arduino usage

### ISSUE THREAD

**Issue by mcer12** [soanvig/mm-jsr#93]
Hi, first off, this looks great and is probably the only nicely fleshed out range slider library that doens't need jquery.

Since I want to use this on an arduino project and have to embed it in the code by hand, it would help tremendously if you included the files precompiled (minified or not) so I can copy the code there.

**Comment by soanvig** [comment]
Hello, thanks there

I don't include compiled code in repo, because it bloats the repository itself. You may however download it from npm directly using unpkg: https://unpkg.com/mm-jsr/

There you can browse compiled files and download them (`index.js` primarily). They are already minified. Types directory is not required, it is only helpful for IDE or compilation process as dependency in other projects.

Does this suit your case?

**Comment by mcer12** [comment]
Awesome, thank you!

út 18. 5. 2021 v 20:46 odesílatel Mateusz Koteja ***@***.***>
napsal:

**Comment by soanvig** [comment]
Super! If You need any help or some code changes, let me know in this issue. I'm eager to help. I will leave this open issue for a while.

**Comment by mcer12** [comment]
@soanvig Regarding your question... it is Arduino project but actually ESP8266 which is a wifi module and can host small websites :)

**Comment by soanvig** [comment]
@mcer12  how's going? Can we close this issue, or do you need some support?

**Comment by mcer12** [comment]
Feel free to close it, I will create a new issue if there’s a problem ;)
